brand_name:
  default: ""
website_url:
  default: ""
logo_url:
  default: ""
mobile_logo_url:
  default: ""
links:
  type: list
  list_type: simple
  default: ""
icons:
  type: list
  list_type: simple
  default: ""
custom_font_awesome_icons:
  type: list
  list_type: simple
  default: ""
